"""Build reviewable, privacy-safe GitHub failure reports."""

from __future__ import annotations

from hashlib import sha256
import json
from typing import Any, Mapping, Sequence
from urllib.parse import urlencode

ISSUE_URL = "https://github.com/jmping/ha-open-data/issues/new"
_ALLOWED_CONTEXT_KEYS = {
    "provider",
    "portal_url",
    "dataset_id",
    "resource_id",
    "stage",
    "error_type",
    "error_message",
    "integration_version",
    "home_assistant_version",
    "timezone",
    "temporal_status",
    "timestamp_fields",
    "metric_fields",
    "identity_fields",
    "source_ordering",
}


def _clean_scalar(value: Any, *, limit: int = 500) -> str | None:
    if value is None:
        return None
    text = str(value).replace("\r", " ").replace("\n", " ").strip()
    if not text:
        return None
    return text[:limit]


def _clean_fields(value: Any) -> list[str]:
    if not isinstance(value, (list, tuple, set)):
        return []
    return sorted(
        {
            cleaned
            for item in value
            if (cleaned := _clean_scalar(item, limit=120)) is not None
        }
    )[:100]


def sanitize_failure_context(context: Mapping[str, Any]) -> dict[str, Any]:
    """Retain identifiers/schema evidence while excluding raw rows and secrets."""
    result: dict[str, Any] = {}
    for key in _ALLOWED_CONTEXT_KEYS:
        if key not in context:
            continue
        if key.endswith("_fields"):
            result[key] = _clean_fields(context[key])
            continue
        cleaned = _clean_scalar(context[key])
        if cleaned is not None:
            result[key] = cleaned
    return result


def failure_fingerprint(context: Mapping[str, Any]) -> str:
    """Return a stable signature suitable for deduplicating recurring failures."""
    sanitized = sanitize_failure_context(context)
    signature = {
        key: sanitized.get(key)
        for key in (
            "provider",
            "stage",
            "error_type",
            "timestamp_fields",
            "metric_fields",
            "identity_fields",
        )
    }
    encoded = json.dumps(signature, sort_keys=True, separators=(",", ":")).encode()
    return sha256(encoded).hexdigest()[:16]


def build_failure_report(context: Mapping[str, Any]) -> dict[str, Any]:
    """Return sanitized report metadata and a prefilled GitHub issue URL."""
    sanitized = sanitize_failure_context(context)
    fingerprint = failure_fingerprint(sanitized)
    provider = sanitized.get("provider", "unknown provider")
    stage = sanitized.get("stage", "unknown stage")
    error_type = sanitized.get("error_type", "import failure")
    title = f"Import failure: {provider} / {stage} / {error_type}"

    lines = [
        "## Open Data import failure",
        "",
        f"Failure fingerprint: `{fingerprint}`",
        "",
        "This report was generated by Home Assistant Open Data. It intentionally excludes raw dataset rows, credentials, headers, cookies, and tokens.",
        "",
        "### Sanitized diagnostics",
        "",
        "```json",
        json.dumps(sanitized, indent=2, ensure_ascii=False, sort_keys=True),
        "```",
        "",
        "### What happened?",
        "",
        "Please add any visible UI symptoms or steps needed to reproduce the problem.",
    ]
    body = "\n".join(lines)
    issue_url = f"{ISSUE_URL}?{urlencode({'template': 'import-failure.md', 'title': title, 'body': body})}"
    return {
        "fingerprint": fingerprint,
        "sanitized": sanitized,
        "title": title,
        "body": body,
        "issue_url": issue_url,
        "privacy": "No raw row values or authentication material are included by default.",
    }
